.travis.yml:

language: java
sudo: false

jdk:
- oraclejdk8

test:
  adapter: mysql2
  database: myapp_test
  username: travis
  encoding: utf8

before_script:
  - npm init
  - mysql -u root -e 'create database test;'
  - mysql -u root test < tables.sql

script:

after_success:
- ./gradlew jacocoTestReport coveralls

env:
  global:
    - CI_NAME=travis-ci
